/*
 * obj_fatfs.h
 *
 * Created: 7/22/2022 6:52:58 AM
 *  Author: Adam
 */ 


#ifndef OBJ_FATFS_H_
#define OBJ_FATFS_H_

#include <stdint.h>
#include <stdbool.h>

#define OBJ_FATFS_MBR_JMPBOOT_LEN			3
#define OBJ_FATFS_MBR_JMPBOOT_SHIFT			0
#define OBJ_FATFS_MBR_CODE_AREA_LEN			437
#define OBJ_FATFS_MBR_CODE_AREA_SHIFT		(OBJ_FATFS_MBR_JMPBOOT_SHIFT + OBJ_FATFS_MBR_JMPBOOT_LEN)
#define OBJ_FATFS_MBR_DISK_SIGN_LEN			4
#define OBJ_FATFS_MBR_DISK_SIGN_SHIFT		(OBJ_FATFS_MBR_CODE_AREA_SHIFT + OBJ_FATFS_MBR_CODE_AREA_LEN)
#define OBJ_FATFS_MBR_COPY_PROTECT_LEN		2
#define OBJ_FATFS_MBR_COPY_PROTECT_SHIFT	(OBJ_FATFS_MBR_DISK_SIGN_SHIFT + OBJ_FATFS_MBR_DISK_SIGN_LEN)
#define OBJ_FATFS_MBR_PART_ENTR_1_LEN		16
#define OBJ_FATFS_MBR_PART_ENTR_1_SHIFT		(OBJ_FATFS_MBR_COPY_PROTECT_SHIFT + OBJ_FATFS_MBR_COPY_PROTECT_LEN)
#define OBJ_FATFS_MBR_PART_ENTR_2_LEN		16
#define OBJ_FATFS_MBR_PART_ENTR_2_SHIFT		(OBJ_FATFS_MBR_PART_ENTR_1_SHIFT + OBJ_FATFS_MBR_PART_ENTR_1_LEN)
#define OBJ_FATFS_MBR_PART_ENTR_3_LEN		16
#define OBJ_FATFS_MBR_PART_ENTR_3_SHIFT		(OBJ_FATFS_MBR_PART_ENTR_2_SHIFT + OBJ_FATFS_MBR_PART_ENTR_2_LEN)
#define OBJ_FATFS_MBR_PART_ENTR_4_LEN		16
#define OBJ_FATFS_MBR_PART_ENTR_4_SHIFT		(OBJ_FATFS_MBR_PART_ENTR_3_SHIFT + OBJ_FATFS_MBR_PART_ENTR_3_LEN)
#define OBJ_FATFS_MBR_SIGNTATURE_W_LEN		2
#define OBJ_FATFS_MBR_SIGNTATURE_W_SHIFT	(OBJ_FATFS_MBR_PART_ENTR_4_SHIFT + OBJ_FATFS_MBR_PART_ENTR_4_LEN)

#define OBJ_FATFS_MBR_COPY_PROTECT			0x5A5A
#define OBJ_FATFS_MBR_COPY_NON_PROTECT		0x0000

#define OBJ_FATFS_MBR_SIGNATURE_WORD		0xAA55

#define OBJ_FATFS_MBR_PART_EN_STATUS_LEN	1
#define OBJ_FATFS_MBR_PART_EN_STATUS_SHIFT	0
#define OBJ_FATFS_MBR_PART_EN_FS_CHS_LEN	3 //first absolute sector address
#define OBJ_FATFS_MBR_PART_EN_FS_CHS_SHIFT	(OBJ_FATFS_MBR_PART_EN_STATUS_SHIFT + OBJ_FATFS_MBR_PART_EN_STATUS_LEN)
#define OBJ_FATFS_MBR_PART_TYPE_LEN			1
#define	OBJ_FATFS_MBR_PART_TYPE_SHIFT		(OBJ_FATFS_MBR_PART_EN_FS_CHS_SHIFT + OBJ_FATFS_MBR_PART_EN_FS_CHS_LEN)
#define OBJ_FATFS_MBR_PART_EN_LS_CHS_LEN	3 //last absolute sector address
#define OBJ_FATFS_MBR_PART_EN_FS_CHS_SHIFT	(OBJ_FATFS_MBR_PART_TYPE_SHIFT + OBJ_FATFS_MBR_PART_TYPE_LEN)
#define OBJ_FATFS_MBR_PART_FS_LBA_LEN		4
#define OBJ_FATFS_MBR_PART_FS_LBA_SHIFT		(OBJ_FATFS_MBR_PART_EN_FS_CHS_SHIFT + OBJ_FATFS_MBR_PART_EN_LS_CHS_LEN)
#define OBJ_FATFS_MBR_PART_SEC_IN_PART_LEN	4
#define OBJ_FATFS_MBR_PART_SEC_IN_PART_SHIFT (OBJ_FATFS_MBR_PART_FS_LBA_SHIFT + OBJ_FATFS_MBR_PART_FS_LBA_LEN)

#define OBJ_FATFS_MBR_PART_TYPE_EMPTY		0x00
#define OBJ_FATFS_MBR_PART_TYPE_NTFS		0x07
#define OBJ_FATFS_MBR_PART_TYPE_FAT32_CHS	0x0B
#define OBJ_FATFS_MBR_PART_TYPE_FAT32_LBA	0x0C
#define OBJ_FATFS_MBR_PART_TYPE_EXTEND_LBA	0x0F
#define OBJ_FATFS_MBR_PART_TYPE_LINUX_SS	0x82 //linux swap space
#define OBJ_FATFS_MBR_PART_TYPE_LINUX_FS	0x83



#endif /* OBJ_FATFS_H_ */